# Generated by Django 2.2 on 2020-04-25 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_comment_myuser_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img_link',
            field=models.CharField(default='https://i1.imageban.ru/out/2017/12/11/e7afe65c4f3028db5e2127f32740ac3d.jpg', max_length=1000),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='categoryName', max_length=1000),
        ),
        migrations.AlterField(
            model_name='category',
            name='time',
            field=models.CharField(default='0 hr 15 min', max_length=1000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='login',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='lname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default='https://i1.imageban.ru/out/2017/12/11/e7afe65c4f3028db5e2127f32740ac3d.jpg', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='methods',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.CharField(default='0.0', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.CharField(default='0 hr 15 min', max_length=1000),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
