# Generated by Django 2.2 on 2020-04-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200425_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='isSuperUser',
            new_name='is_superuser',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='lname',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='login',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='name',
        ),
        migrations.AddField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
